name: build

on: 
  push:
    branches-ignore: continuous
    tags-ignore: continuous
  pull_request:
    branches-ignore: continuous

# This ensures that jobs get canceled when force-pushing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# The default Debian shell (dash) is faster than bash at running scripts,
# and using bash when it is not needed doesn't make sense.
defaults:
  run:
    shell: sh

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x86_64 ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      env:
        ARCHITECTURE: ${{ matrix.arch }}
      run: |
           set -x
           set -e
           cd make-static-appimage
           # go mod init
           go get -u ./...
           CGO_ENABLED=0 go build -ldflags="-s -w" -o="../dist/make-static-appimage_${{ matrix.arch }}"
           cd ..
           cd static-appimage-runtime
           # go mod init
           go get -u ./...
           CGO_ENABLED=0 go build -ldflags="-s -w" -o="../dist/static-appimage-runtime_${{ matrix.arch }}"
           mkdir make-static-appimage.AppDir
           cp "../dist/static-appimage-runtime_${{ matrix.arch }}" make-static-appimage.AppDir/AppRun
           "../dist/make-static-appimage_${{ matrix.arch }}" make-static-appimage.AppDir "../dist/make-static-appimage_${{ matrix.arch }}.AppImage"
           EOF
           cd ..

    - name: Upload to releases
      if: github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: continuous
